DROP TABLE IF EXISTS users;


CREATE TABLE users(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL,
    password TEXT NOT NULL,
    email TEXT NOT NULL
);

DROP TABLE IF EXISTS watchlist;

CREATE TABLE watchlist(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    stock TEXT,
    ticker VARCHAR(5) NOT NULL,
    price DECIMAL NOT NULL,
    users_id INT REFERENCES users(id)
);